movie_genres = [
    "Action",
    "Adventure",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Film Noir",
    "History",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Sports",
    "Superhero",
    "Thriller",
    "War",
    "Western",
    "Action-Adventure",
    "Dark Comedy",
    "Epic",
    "Spy",
    "Survival",
    "Slasher",
    "Zombie",
    "Martial Arts",
    "Silent Film",
    "Coming-of-Age",
    "Disaster",
    "Heist",
    "Psychological Thriller",
    "Found Footage",
    "Mockumentary",
    "Cyberpunk",
    "Steampunk",
    "Gothic Horror",
    "Splatter",
    "Teen",
    "Tragedy",
    "Satire",
    "Parody",
    "Political Thriller",
    "Legal Drama",
    "Courtroom Drama",
    "Anthology",
    "Space Opera",
    "Post-Apocalyptic",
    "Road Movie",
    "Musical Comedy",
    "Political Satire",
    "Buddy",
    "Caper",
    "Sword and Sandal",
    "Ghost",
    "Cult",
    "Kaiju",
    "Urban",
    "Dance",
    "Period Drama",
    "Art House",
    "Psychological Horror",
    "Existential Drama",
    "Neo-Noir",
    "Time Travel",
    "Erotic Thriller",
    "Vampire",
    "Werewolf",
    "Monster",
    "Supernatural",
    "Fantasy Adventure",
    "Science Fantasy",
    "Romantic Comedy",
    "Romantic Drama",
    "Romantic Thriller",
    "Black Comedy",
    "Spaghetti Western",
    "Crime Thriller",
    "Gangster",
    "Road",
    "Musical Drama",
    "Dance Drama",
    "Historical Fiction",
    "Melodrama"
]