# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(831, 651)
        self.frameFormulario = QtWidgets.QFrame(parent=Form)
        self.frameFormulario.setGeometry(QtCore.QRect(10, 70, 811, 141))
        self.frameFormulario.setStyleSheet("#frameFormulario {\n"
"  background-color: #fff;\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"}\n"
"#frameFormulario QLabel,\n"
"#frameFormulario QLineEdit,\n"
"#frameFormluario QComboBox{\n"
"  font-family: Segoe UI Semibold;\n"
"  font-size: 12px;\n"
"}\n"
"\n"
"#frameFormulario QLineEdit,\n"
"#frameFormulario QComboBox{\n"
"  padding: 4px 5px;\n"
"  border: 1px solid #838383;\n"
"  border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"#frameFormulario QLineEdit:focus,\n"
"#frameFormulario  QComboBox:focus{\n"
"border-color: #0055ff;\n"
"}\n"
"\n"
"QComboBox:drop-down{\n"
"  background: transparent;\n"
"  border: none;\n"
"  margin-right: 5px;\n"
"}\n"
"")
        self.frameFormulario.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameFormulario.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameFormulario.setObjectName("frameFormulario")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameFormulario)
        self.gridLayout_3.setContentsMargins(30, 20, 30, 20)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_lastName = QtWidgets.QLabel(parent=self.frameFormulario)
        self.label_lastName.setObjectName("label_lastName")
        self.gridLayout.addWidget(self.label_lastName, 2, 0, 1, 1)
        self.txt_studentID = QtWidgets.QLineEdit(parent=self.frameFormulario)
        self.txt_studentID.setObjectName("txt_studentID")
        self.gridLayout.addWidget(self.txt_studentID, 0, 1, 1, 1)
        self.label_firstName = QtWidgets.QLabel(parent=self.frameFormulario)
        self.label_firstName.setObjectName("label_firstName")
        self.gridLayout.addWidget(self.label_firstName, 1, 0, 1, 1)
        self.label_stundentID = QtWidgets.QLabel(parent=self.frameFormulario)
        self.label_stundentID.setObjectName("label_stundentID")
        self.gridLayout.addWidget(self.label_stundentID, 0, 0, 1, 1)
        self.txt_firstName = QtWidgets.QLineEdit(parent=self.frameFormulario)
        self.txt_firstName.setObjectName("txt_firstName")
        self.gridLayout.addWidget(self.txt_firstName, 1, 1, 1, 1)
        self.txt_lastName = QtWidgets.QLineEdit(parent=self.frameFormulario)
        self.txt_lastName.setObjectName("txt_lastName")
        self.gridLayout.addWidget(self.txt_lastName, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_state = QtWidgets.QLabel(parent=self.frameFormulario)
        self.label_state.setObjectName("label_state")
        self.gridLayout_2.addWidget(self.label_state, 0, 0, 1, 1)
        self.cb_state = QtWidgets.QComboBox(parent=self.frameFormulario)
        self.cb_state.setObjectName("cb_state")
        self.gridLayout_2.addWidget(self.cb_state, 0, 1, 1, 1)
        self.label_city = QtWidgets.QLabel(parent=self.frameFormulario)
        self.label_city.setObjectName("label_city")
        self.gridLayout_2.addWidget(self.label_city, 1, 0, 1, 1)
        self.cb_city = QtWidgets.QComboBox(parent=self.frameFormulario)
        self.cb_city.setObjectName("cb_city")
        self.gridLayout_2.addWidget(self.cb_city, 1, 1, 1, 1)
        self.label_emailAddress = QtWidgets.QLabel(parent=self.frameFormulario)
        self.label_emailAddress.setObjectName("label_emailAddress")
        self.gridLayout_2.addWidget(self.label_emailAddress, 2, 0, 1, 1)
        self.txt_emailAddress = QtWidgets.QLineEdit(parent=self.frameFormulario)
        self.txt_emailAddress.setObjectName("txt_emailAddress")
        self.gridLayout_2.addWidget(self.txt_emailAddress, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.frameBotones = QtWidgets.QFrame(parent=Form)
        self.frameBotones.setGeometry(QtCore.QRect(10, 220, 811, 61))
        self.frameBotones.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.frameBotones.setStyleSheet("#frameBotones QPushButton,\n"
"QHeaderView:section{\n"
"  font-family: Segoe UI Semibold;\n"
"  font-size: 12px;\n"
"}\n"
"\n"
"#frameBotones QPushButton{\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #f0f0f0;\n"
"    border-radius: 5px;\n"
"    background-color: #85eBf7;\n"
"}\n"
"\n"
"#frameBotones QPushButton:hover{\n"
"    border-color: #4c96f7;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#frameBotones #delete_button{\n"
"    background-color: #ff8183;\n"
"}\n"
"\n"
"#frameBotones #delete_button:hover{\n"
"    border-color: #dc0004;\n"
"}\n"
"\n"
"")
        self.frameBotones.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameBotones.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameBotones.setObjectName("frameBotones")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frameBotones)
        self.gridLayout_5.setContentsMargins(30, 10, 30, 10)
        self.gridLayout_5.setHorizontalSpacing(15)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.add_button = QtWidgets.QPushButton(parent=self.frameBotones)
        self.add_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../icons/plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_button.setIcon(icon)
        self.add_button.setIconSize(QtCore.QSize(20, 20))
        self.add_button.setObjectName("add_button")
        self.gridLayout_5.addWidget(self.add_button, 0, 0, 1, 1)
        self.update_button = QtWidgets.QPushButton(parent=self.frameBotones)
        self.update_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../icons/refresh.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.update_button.setIcon(icon1)
        self.update_button.setIconSize(QtCore.QSize(20, 20))
        self.update_button.setObjectName("update_button")
        self.gridLayout_5.addWidget(self.update_button, 0, 1, 1, 1)
        self.select_button = QtWidgets.QPushButton(parent=self.frameBotones)
        self.select_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../icons/select.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_button.setIcon(icon2)
        self.select_button.setIconSize(QtCore.QSize(20, 20))
        self.select_button.setObjectName("select_button")
        self.gridLayout_5.addWidget(self.select_button, 0, 2, 1, 1)
        self.search_button = QtWidgets.QPushButton(parent=self.frameBotones)
        self.search_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\../icons/search.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_button.setIcon(icon3)
        self.search_button.setIconSize(QtCore.QSize(20, 20))
        self.search_button.setObjectName("search_button")
        self.gridLayout_5.addWidget(self.search_button, 0, 3, 1, 1)
        self.clear_button = QtWidgets.QPushButton(parent=self.frameBotones)
        self.clear_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\../icons/delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clear_button.setIcon(icon4)
        self.clear_button.setIconSize(QtCore.QSize(20, 20))
        self.clear_button.setObjectName("clear_button")
        self.gridLayout_5.addWidget(self.clear_button, 0, 4, 1, 1)
        self.delete_button = QtWidgets.QPushButton(parent=self.frameBotones)
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\../icons/trash.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_button.setIcon(icon5)
        self.delete_button.setIconSize(QtCore.QSize(20, 20))
        self.delete_button.setObjectName("delete_button")
        self.gridLayout_5.addWidget(self.delete_button, 0, 5, 1, 1)
        self.frameData = QtWidgets.QFrame(parent=Form)
        self.frameData.setGeometry(QtCore.QRect(10, 290, 811, 331))
        self.frameData.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameData.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameData.setObjectName("frameData")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frameData)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.table = QtWidgets.QTableWidget(parent=self.frameData)
        self.table.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.table.setStyleSheet("#frameData {\n"
"  border-radius: 5px;\n"
"  background-color: #fff;\n"
"}\n"
"\n"
"QTableWidget{\n"
"  border-radius: 3px;\n"
"  border: 1px solid #f0f0f0;\n"
"}\n"
"QHeaderView:section{\n"
"  border: none;\n"
"  border-bottom: 1px solid #d0c6ff;\n"
"  text-align: left;\n"
"  font-weight: 350;\n"
"  padding: 3px 5px;\n"
"}\n"
"\n"
"QTableWidget:item{\n"
"  border-bottom: 1px solid #d0c6ff;\n"
"  color: #000;\n"
"  padding-left: 3px;\n"
"}")
        self.table.setShowGrid(False)
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(120)
        self.table.horizontalHeader().setMinimumSectionSize(50)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.table, 0, 0, 1, 1)
        self.frameTitulo = QtWidgets.QFrame(parent=Form)
        self.frameTitulo.setGeometry(QtCore.QRect(10, 10, 811, 51))
        self.frameTitulo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameTitulo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameTitulo.setObjectName("frameTitulo")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frameTitulo)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_title = QtWidgets.QLabel(parent=self.frameTitulo)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_4.addWidget(self.label_title, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_lastName.setText(_translate("Form", "Last Name"))
        self.label_firstName.setText(_translate("Form", "First Name"))
        self.label_stundentID.setText(_translate("Form", "Student ID"))
        self.label_state.setText(_translate("Form", "State"))
        self.label_city.setText(_translate("Form", "City"))
        self.label_emailAddress.setText(_translate("Form", "Email Address"))
        self.add_button.setText(_translate("Form", "Add"))
        self.update_button.setText(_translate("Form", "Update"))
        self.select_button.setText(_translate("Form", "Select"))
        self.search_button.setText(_translate("Form", "Search"))
        self.clear_button.setText(_translate("Form", "Clear"))
        self.delete_button.setText(_translate("Form", "Delete"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Student ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "First Name"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Last Name"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "State"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "City"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Email Address"))
        self.label_title.setText(_translate("Form", "Students Information System"))
