/*                  SOLUCIONES:
1. CREAR UNA MINI-INTERFAZ PARA INTRODUCIR LAS NOTAS.
2. VALIDAR QUE NO HAYA ERRORRES.
3. SE DEBE PROMEDIAR LA NOTA DEL PROFESOR, CON OTRAS DOS
NOTAS DE TRABAJOS ANTERIORES.
4. SI EL PROMEDIO ES MAYOR A 7/10 ENTONCES APROBÓ LA MATERIA.
*/